config/routes.rb
Pickfive::Application.routes.draw do

  resources :users
  resources :app_configs
  match ':controller(/:action(/:id))(.:format)', via: [:get, :post]
  root :to => 'sessions#login'
  match "editsettings" => "editsettings#index", via: [:get, :post]
  match "login" => "sessions#login", via: [:get, :post]
  match "logout" => "sessions#logout", via: [:get, :post]
  match "gamepicks" => "gamepicks#index", via: [:get, :post]
  match "grouppicks" => "grouppicks#index", via: [:get, :post]
  match "enterspreads" => "enterspreads#index", via: [:get, :post]
  match "displayspreads" => "displayspreads#index", via: [:get, :post]
  match "users" => "users#index", via: [:get, :post]
  match "app_configs" => "app_configs#index", via: [:get, :post]

end

app/models/app_config.rb
class AppConfig < ActiveRecord::Base
	self.table_name = "app_config"
end

app/controllers/app_configs_controller.rb
class AppConfigsController < ApplicationController
  before_action :set_config, only: [:show, :edit, :update, :destroy]
  before_action :load_variables

  def index
    @configs = AppConfig.all
  end

  # GET /appconfig/1/edit
  def edit
  end

  def create
    @config = AppConfig.new(config_params)
    if @config.save
      flash[:notice] = "Your changes have been saved successfully."
      flash[:color] = "valid"
      redirect_to action: "index"
    else
      sErr = ""
      user.errors.full_messages.each do |message|
        sErr = sErr + " " + message
      end
      flash[:notice] = sErr
      flash[:color] = "invalid"
      redirect_to action: "index"
    end
  end

  # PATCH/PUT /appconfig/1
  def update
      if @config.update(config_params)
        flash[:notice] = "Your changes have been saved successfully."
        flash[:color] = "valid"
        redirect_to action: "edit"
      else
        sErr = ""
        user.errors.full_messages.each do |message|
          sErr = sErr + " " + message
        end
        flash[:notice] = sErr
        flash[:color] = "invalid"
        redirect_to action: "edit"
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_config
      @config = AppConfig.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def config_params
      params.require(:app_config).permit(:name, :value)
    end
end

app/controllers/appconfig_controller.rb
class AppconfigController < ApplicationController
  before_action :set_config, only: [:show, :edit, :update, :destroy]
  before_action :load_variables

  def index
    @configs = AppConfig.all
  end

  # GET /appconfig/1/edit
  def edit
  end

  def create
    @config = AppConfig.new(config_params)
    if @config.save
      flash[:notice] = "Your changes have been saved successfully."
      flash[:color] = "valid"
      redirect_to action: "index"
    else
      sErr = ""
      user.errors.full_messages.each do |message|
        sErr = sErr + " " + message
      end
      flash[:notice] = sErr
      flash[:color] = "invalid"
      redirect_to action: "index"
    end
  end

  # PATCH/PUT /appconfig/1
  def update
      if @user.update(config_params)
        flash[:notice] = "Your changes have been saved successfully."
        flash[:color] = "valid"
        redirect_to action: "edit"
      else
        sErr = ""
        user.errors.full_messages.each do |message|
          sErr = sErr + " " + message
        end
        flash[:notice] = sErr
        flash[:color] = "invalid"
        redirect_to action: "edit"
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_config
      @config = AppConfig.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def config_params
      params.require(:appconfig).permit(:name, :value)
    end
end

app/helpers/app_configs_helper.rb
module AppConfigsHelper
end

app/views/app_configs/_form.html.erb
<div class="body">
  <%= render partial: "shared/navBar", locals: {type: "admin"}  %>
    <% if flash[:color]== "invalid"%>
        <div id="flash-err-wrapper" class="flash">
            <div id="flash-err"><%=flash[:notice]%></div>
        </div>
    <% elsif flash[:color] == "valid" %>
        <div id="flash-message-wrapper" class="flash">
            <div id="flash-message"><%=flash[:notice]%></div>
        </div>
    <%end%>
    <br>
<%= form_for(config) do |f| %>
  Name : <%= f.text_field :name, size: 30%><br />
  Value : <%= f.text_field :value, size: 30 %><br /><br />

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/app_configs/edit.html.erb
<h1>Editing AppConfig</h1>

<%= render 'form', config: @config %>

<%= link_to 'Back', app_configs_path %>

app/views/app_configs/index.html.erb
<%= render partial: "shared/navBar", locals: {type: "admin"}  %>
    <% if flash[:color]== "invalid"%>
        <div id="flash-err-wrapper" class="flash">
            <div id="flash-err"><%=flash[:notice]%></div>
        </div>
    <% elsif flash[:color] == "valid" %>
        <div id="flash-message-wrapper" class="flash">
            <div id="flash-message"><%=flash[:notice]%></div>
        </div>
    <%end%>
    <br>

<h1>App Config</h1>
<table>
  <thead>
    <tr>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @configs.each do |config| %>
      <tr>
        <td><%=config.name%> = <%=config.value%>&nbsp;&nbsp;</td>
        <td><%= link_to 'Edit', edit_app_config_path(config) %></td>
       </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/app_configs/new.html.erb
<h1>New AppConfig</h1>

<%= render 'form', config: @config %>

<%= link_to 'Back', app_configs_path %>